name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/my-back-end .
        docker push ${{ secrets.DOCKER_USERNAME }}/my-back-end

  
  deploy: 
    needs: build
    runs-on: aws-ec2    
    steps:
      - name: Pull image from docker hub
        run: docker pull kasunkalharabamunuarachchi123/my-back-end:latest 
      - name: Delete Old Container
        run: docker rm -f my-back-end
      - name: Run docker container
        run: docker run -d -p 5000:5000 --name my-back-end kasunkalharabamunuarachchi123/my-back-end   
